views/check_ssh.py
import asyncio
import json

import flask
from flask_socketio import Namespace

import controllers
import models


# noinspection PyMethodMayBeStatic
class CheckSSHNamespace(Namespace):
    def __init__(self, namespace):
        super().__init__(namespace)
        self.loop = asyncio.new_event_loop()
        self.semaphore = asyncio.Semaphore(int(models.get_settings()['process_count']), loop=self.loop)
        self.future = None

    def on_connect(self):
        self.emit('update_ssh_lists', {
            'live': models.get_ssh_live_list(),
            'die': models.get_ssh_die_list()
        })

    def on_check_ssh(self):
        ssh_list = models.get_ssh_list()
        self.on_clear_live()
        self.on_clear_die()

        if self.loop.is_running() is False:
            coros = [self.check_ssh_handler(ssh) for ssh in ssh_list]
            fut = asyncio.gather(*coros, loop=self.loop)
            self.loop.run_until_complete(fut)

    async def check_ssh_handler(self, ssh):
        async with self.semaphore:
            if await controllers.verify_ssh(*ssh.values()):
                models.set_ssh_live_list(models.get_ssh_live_list() + [ssh])
                self.emit('live', ssh)
            else:
                models.set_ssh_die_list(models.get_ssh_die_list() + [ssh])
                self.emit('die', ssh)

    def on_clear_live(self):
        models.set_ssh_live_list([])
        self.emit('clear_live')

    def on_clear_die(self):
        models.set_ssh_die_list([])
        self.emit('clear_die')


check_ssh_blueprint = flask.Blueprint('check_ssh', 'check_ssh')


@check_ssh_blueprint.route('')
def check_ssh():
    return flask.send_file('templates/check-ssh.html')


@check_ssh_blueprint.route('/ssh')
def ssh_list():
    return json.dumps(models.get_ssh_list())


@check_ssh_blueprint.route('/live')
def ssh_live_list():
    return json.dumps(models.get_ssh_live_list())


@check_ssh_blueprint.route('/die')
def ssh_die_list():
    return json.dumps(models.get_ssh_die_list())

views/connect_ssh.py
import asyncio
import json
from typing import Optional

import flask
from flask_socketio import Namespace

import controllers
import models

current_pool: Optional[controllers.ProxyPool] = None


# noinspection PyMethodMayBeStatic
class ConnectSSHNamespace(Namespace):
    def __init__(self, namespace):
        super().__init__(namespace)
        self.loop = asyncio.new_event_loop()
        self.pool = None

    def on_connect_ssh(self, port_list):
        global current_pool
        if current_pool is None:
            current_pool = self.pool = controllers.ProxyPool(int(models.get_settings()['process_count']), self.loop)
        for ssh in models.get_ssh_list():
            self.pool.add_ssh(ssh['ip'], ssh['username'], ssh['password'])

        if self.loop.is_running() is False:
            aws = [self.pool.proxy_port(port, self.port_proxy_callback) for port in port_list]
            try:
                self.loop.run_until_complete(asyncio.gather(*aws, loop=self.loop))
            except controllers.OutOfSSHError:
                self.emit('out_of_ssh')

    def on_reset_port(self, port):
        if self.pool is not None:
            self.pool.reset_port(port)

    def on_disconnect_all_ssh(self):
        if self.pool is not None:
            self.pool.disconnect_all_ports()
            global current_pool
            current_pool = self.pool = None

    def port_proxy_callback(self, port, ip):
        data = {'port': port, 'ip': ip}
        self.emit('port_proxy', data)


connect_ssh_blueprint = flask.Blueprint('connect_ssh', 'connect_ssh')


@connect_ssh_blueprint.route('')
def connect_ssh():
    return flask.send_file('templates/connect-ssh.html')


@connect_ssh_blueprint.route('/ssh')
def ssh_list():
    return json.dumps(models.get_ssh_list())


@connect_ssh_blueprint.route('/port-info')
def port_info():
    if current_pool is not None:
        return json.dumps(current_pool.get_all_port_info())
    return '{}'


@connect_ssh_blueprint.route('/out-of-ssh')
def out_of_ssh_check():
    if current_pool is not None:
        return '1' if current_pool.out_of_ssh() else '0'
    return '1'

templates/check-ssh.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>SSHManager</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.12.0/css/all.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="/assets/fonts/fontawesome5-overrides.min.css?h=a436bee1e5ae414f98db7ca13adfd7c0">
    <link rel="stylesheet" href="/assets/css/Footer-Basic.css?h=d15dfcb68fabe0442ff06063b052477c">
    <link rel="stylesheet" href="/assets/css/Navigation-with-Button.css?h=b486ae8ecf6c38e7b0073c57ef30f22f">
    <link rel="stylesheet" href="/assets/css/styles.css?h=d41d8cd98f00b204e9800998ecf8427e">
<script src="https://cdn.jsdelivr.net/npm/vue@2.6.12/dist/vue.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.0.1/socket.io.js"></script>
</head>

<body>
    <div class="container" id="main-app">
        <div class="modal fade" role="dialog" tabindex="-1" id="settings-modal">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title">Settings</h4><button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
                    </div>
                    <div class="modal-body">
                        <div class="input-group">
                            <div class="input-group-prepend"><span class="input-group-text">Max SSH processes</span></div><input class="form-control" type="number" min="1" step="1" v-model="temp_settings.process_count">
                            <div class="input-group-append"></div>
                        </div>
                    </div>
                    <div class="modal-footer"><button class="btn btn-light" type="button" data-dismiss="modal">Close</button><button class="btn btn-primary" type="button" v-on:click="settings = temp_settings" data-toggle="modal" data-target="#settings-modal" onclick="main_socket.emit(&#39;settings&#39;, vm.$data.settings)">Save</button></div>
                </div>
            </div>
        </div>
        <div class="modal fade" role="dialog" tabindex="-1" id="import-ssh-modal">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title">Import SSH</h4><button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
                    </div>
                    <div class="modal-body"><textarea placeholder="1.2.3.4|user|pass" style="width: 100%;" rows="10" onchange="vm.$data.ssh_text = this.value"></textarea></div>
                    <div class="modal-footer"><button class="btn btn-light" type="button" data-dismiss="modal">Close</button><button class="btn btn-primary" type="button" onclick="import_ssh_text(vm.$data.ssh_text)" data-toggle="modal" data-target="#import-ssh-modal">Import</button></div>
                </div>
            </div>
        </div>
        <nav class="navbar navbar-light navbar-expand-md sticky-top navigation-clean-button mb-1">
            <div class="container-fluid"><a class="navbar-brand" href="#">SSH Manager</a><button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navcol-1">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item"><a class="nav-link" href="/check-ssh">Check SSH</a></li>
                        <li class="nav-item"><a class="nav-link" href="/connect-ssh">Connect SSH</a></li>
                    </ul><span class="navbar-text actions"> <button class="btn btn-light action-button" type="button" data-toggle="modal" data-target="#settings-modal" v-on:click="temp_settings = settings">Settings</button></span>
                </div>
            </div>
        </nav>
        <div class="row">
            <div class="col"><button class="btn btn-primary mx-1" type="button" onclick="check_ssh()">Check SSH</button><button class="btn btn-outline-primary mx-1" type="button" data-toggle="modal" data-target="#import-ssh-modal" v-on:onclick="ssh_text = ''">Import SSH</button></div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <div class="row align-items-center">
                    <div class="col">
                        <h1 class="text-left">SSH</h1>
                    </div>
                    <div class="col text-right">
                        <div class="btn-group"><button class="btn btn-primary" type="button" onclick="export_csv(vm.$data.ssh_list, &#39;ssh.txt&#39;)">Export</button><button class="btn btn-primary dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-expanded="false" type="button"></button>
                            <div class="dropdown-menu"><a class="dropdown-item" href="#" v-on:click="ssh_list = []" onclick="main_socket.emit(&#39;ssh&#39;, [])">Delete list</a></div>
                        </div>
                    </div>
                </div>
                <div class="table-responsive">
                    <table class="table table-sm">
                        <thead>
                            <tr>
                                <th>IP ({{ ssh_list.length }})</th>
                                <th>User</th>
                                <th>Pass</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr v-for="ssh in ssh_list" :key="ssh.ip">
                                <td>{{ssh.ip}}</td>
                                <td>{{ssh.username}}</td>
                                <td>{{ssh.password}}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="col-md-4">
                <div class="row align-items-center">
                    <div class="col">
                        <h1 class="text-left text-success">Live</h1>
                    </div>
                    <div class="col text-right">
                        <div class="btn-group"><button class="btn btn-primary" type="button" onclick="export_csv(vm.$data.ssh_live_list, &#39;live.txt&#39;)">Export</button><button class="btn btn-primary dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-expanded="false" type="button"></button>
                            <div class="dropdown-menu"><a class="dropdown-item" href="#" v-on:click="ssh_live_list = []" onclick="socket.emit(&#39;clear_live&#39;)">Delete list</a></div>
                        </div>
                    </div>
                </div>
                <div class="table-responsive">
                    <table class="table table-sm">
                        <thead>
                            <tr>
                                <th>IP ({{ ssh_live_list.length }})<br></th>
                                <th>User</th>
                                <th>Pass</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr v-for="ssh in ssh_live_list" :key="ssh.ip">
                                <td>{{ssh.ip}}</td>
                                <td>{{ssh.username}}</td>
                                <td>{{ssh.password}}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="col-md-4">
                <div class="row align-items-center">
                    <div class="col">
                        <h1 class="text-left text-danger">Die</h1>
                    </div>
                    <div class="col text-right">
                        <div class="btn-group"><button class="btn btn-primary" type="button" onclick="export_csv(vm.$data.ssh_die_list, &#39;die.txt&#39;)">Export</button><button class="btn btn-primary dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-expanded="false" type="button"></button>
                            <div class="dropdown-menu"><a class="dropdown-item" href="#" v-on:click="ssh_die_list = []" onclick="socket.emit(&#39;clear_die&#39;)">Delete list</a></div>
                        </div>
                    </div>
                </div>
                <div class="table-responsive">
                    <table class="table table-sm">
                        <thead>
                            <tr>
                                <th>IP&nbsp;({{ ssh_die_list.length }})<br></th>
                                <th>User</th>
                                <th>Pass</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr v-for="ssh in ssh_die_list" :key="ssh.ip">
                                <td>{{ssh.ip}}</td>
                                <td>{{ssh.username}}</td>
                                <td>{{ssh.password}}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="modal fade" role="dialog" tabindex="-1">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title">Modal Title</h4><button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
                    </div>
                    <div class="modal-body">
                        <p>The content of your modal.</p>
                    </div>
                    <div class="modal-footer"><button class="btn btn-light" type="button" data-dismiss="modal">Close</button><button class="btn btn-primary" type="button">Save</button></div>
                </div>
            </div>
        </div>
    </div>
    <footer class="footer-basic">
        <div class="social"><a href="https://facebook.com/khanh.luong.6"><i class="icon ion-social-facebook"></i></a><a href="https://t.me/khanhhne"><i class="fab fa-telegram-plane"></i></a><a href="https://zalo.me/0968259849"><i class="fa fa-phone"></i></a></div>
        <p class="copyright">KhanhhNe © 2021</p>
    </footer>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/js/bootstrap.bundle.min.js"></script>
    <script src="/assets/js/bs-init.js?h=75b741e6afdc9ac33d9fde7f010bc77e"></script>
    <script src="/assets/js/check-ssh.js?h=174bbc889f74b4def8acffa7cf4c523d"></script>
    <script src="/assets/js/vue-app.js?h=31dcc54fab006baede4b185cb32ae2b0"></script>
    <script src="/assets/js/common.js?h=286dec064320f6492d549d2b9540118f"></script>
    <script src="/assets/js/fileSaver.js?h=3dc79a489531e4f96ebcb674709ec092"></script>
</body>

</html>

templates/check_ssh.jinja2
<!--suppress HtmlUnknownAttribute, HtmlFormInputWithoutLabel -->
{% extends 'layout.jinja2' %}

{% block title %}Check SSH{% endblock %}

{% block css %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/check-ssh.css') }}">
{% endblock %}

{% block data %}
{{ macros.ssh_list(['all', 'live', 'die']) }}
{% endblock %}

{% block footer %}
{% raw %}
    <div>
        <button :disabled="checking">Check SSH</button>
        <button class="secondary" :disabled="!checking">Stop</button>
    </div>
    <progress :value="display_progress(progress)"></progress>
{% endraw %}
{% endblock %}

{% block js %}
<script>
    window.data = {
        checking: false,
        progress: undefined
    }
    window.methods = {
        display_progress: function (progress) {
            return isFinite(progress) ? progress : 1;
        }
    }
</script>
{% endblock %}

templates/connect-ssh.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>SSHManager</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.12.0/css/all.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="/assets/fonts/fontawesome5-overrides.min.css?h=a436bee1e5ae414f98db7ca13adfd7c0">
    <link rel="stylesheet" href="/assets/css/Footer-Basic.css?h=d15dfcb68fabe0442ff06063b052477c">
    <link rel="stylesheet" href="/assets/css/Navigation-with-Button.css?h=b486ae8ecf6c38e7b0073c57ef30f22f">
    <link rel="stylesheet" href="/assets/css/styles.css?h=d41d8cd98f00b204e9800998ecf8427e">
<script src="https://cdn.jsdelivr.net/npm/vue@2.6.12/dist/vue.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.0.1/socket.io.js"></script>
</head>

<body>
    <div class="container" id="main-app">
        <div class="modal fade" role="dialog" tabindex="-1" id="settings-modal">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title">Settings</h4><button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
                    </div>
                    <div class="modal-body">
                        <div class="input-group">
                            <div class="input-group-prepend"><span class="input-group-text">Max SSH processes</span></div><input class="form-control" type="number" min="1" step="1" v-model="temp_settings.process_count">
                            <div class="input-group-append"></div>
                        </div>
                    </div>
                    <div class="modal-footer"><button class="btn btn-light" type="button" data-dismiss="modal">Close</button><button class="btn btn-primary" type="button" v-bind:onclick="settings = temp_settings" data-toggle="modal" data-target="#settings-modal" onclick="main_socket.emit(&#39;settings&#39;, vm.$data.settings)">Save</button></div>
                </div>
            </div>
        </div>
        <div class="modal fade" role="dialog" tabindex="-1" id="import-ssh-modal">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title">Import SSH</h4><button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
                    </div>
                    <div class="modal-body"><textarea placeholder="1.2.3.4|user|pass" style="width: 100%;" rows="10" onchange="vm.$data.ssh_text = this.value"></textarea></div>
                    <div class="modal-footer"><button class="btn btn-light" type="button" data-dismiss="modal">Close</button><button class="btn btn-primary" type="button" onclick="import_ssh_text(vm.$data.ssh_text)" data-toggle="modal" data-target="#import-ssh-modal">Import</button></div>
                </div>
            </div>
        </div>
        <nav class="navbar navbar-light navbar-expand-md navigation-clean-button">
            <div class="container"><a class="navbar-brand" href="#">SSH Manager</a><button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navcol-1">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item"><a class="nav-link" href="/check-ssh">Check SSH</a></li>
                        <li class="nav-item"><a class="nav-link active" href="/connect-ssh">Connect SSH</a></li>
                    </ul><span class="navbar-text actions"> <button class="btn btn-light action-button" type="button" data-toggle="modal" data-target="#settings-modal" v-on:click="temp_settings = settings">Settings</button></span>
                </div>
            </div>
        </nav>
        <div class="row">
            <div class="col"><button class="btn btn-primary mx-1" type="button" onclick="connect_ssh()">Connect SSH</button><button class="btn btn-secondary mx-1" type="button" onclick="$(&#39;.reset-port:not(.invisible)&#39;).click()">Reset all port</button><button class="btn btn-danger mx-1" type="button" onclick="socket.emit(&#39;disconnect_all_ssh&#39;)">Disconnect SSH</button><button class="btn btn-outline-primary mx-1" type="button" data-toggle="modal" data-target="#import-ssh-modal" v-bind:onclick="ssh_text = ''">Import SSH</button></div>
        </div>
        <div class="row">
            <div class="col">
                <div class="row">
                    <div class="col">
                        <h3>Connect info</h3>
                    </div>
                </div>
                <div class="input-group" id="connect-ssh-input">
                    <div class="input-group-prepend"><span class="input-group-text">Port</span></div><input class="form-control" type="text" data-toggle="tooltip" data-bss-tooltip="" data-placement="left" id="port-input" name="port" placeholder="1234,1230-1239,..." pattern="^(?:(\d+|(?:\d+-\d+)),)*(\d+|(?:\d+-\d+))$" required="" title="Port number(s) to connect SSH to, seperated by a comma (,). Can be in individual format (12345), range format (1230-1239).">
                    <div class="input-group-append"></div>
                </div>
                <div class="table-responsive">
                    <table class="table table-sm">
                        <thead>
                            <tr>
                                <th>Port</th>
                                <th>IP</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr v-for="proxy in proxy_list" :key="proxy.port" :class="{ 'table-danger': !proxy.ip }">
                                <td>{{proxy.port}}</td>
                                <td>{{proxy.ip}}</td>
                                <td><button class="btn btn-danger btn-sm reset-port" type="button" onclick="socket.emit(&#39;reset_port&#39;, $(this).data(&#39;port&#39;))" v-bind:class="{ invisible: !proxy.ip }" v-bind:data-port="proxy.port">Reset</button></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="col">
                <div class="row">
                    <div class="col">
                        <h3>SSH</h3>
                    </div>
                </div>
                <div class="table-responsive">
                    <table class="table table-sm">
                        <thead>
                            <tr>
                                <th>IP ({{ ssh_list.length }})</th>
                                <th>User</th>
                                <th>Pass</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr v-for="ssh in ssh_list" :key="ssh.ip">
                                <td>{{ssh.ip}}</td>
                                <td>{{ssh.username}}</td>
                                <td>{{ssh.password}}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <footer class="footer-basic">
        <div class="social"><a href="https://facebook.com/khanh.luong.6"><i class="icon ion-social-facebook"></i></a><a href="https://t.me/khanhhne"><i class="fab fa-telegram-plane"></i></a><a href="https://zalo.me/0968259849"><i class="fa fa-phone"></i></a></div>
        <p class="copyright">KhanhhNe © 2021</p>
    </footer>
    <div class="toast fade fixed-top ml-auto my-3 mr-3 hide" role="alert" id="out-of-ssh-toast">
        <div class="toast-header"><strong class="mr-auto">Out of SSH</strong><small>So sad :(</small><button class="close ml-2 mb-1 close" data-dismiss="toast"><span aria-hidden="true">×</span></button></div>
        <div class="toast-body" role="alert">
            <p>Your SSH list has ran out! There will be no new connection for now!</p>
        </div>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/js/bootstrap.bundle.min.js"></script>
    <script src="/assets/js/bs-init.js?h=75b741e6afdc9ac33d9fde7f010bc77e"></script>
    <script src="/assets/js/connect-ssh.js?h=4752bfe83e3799c9ac07b4c11bfdea08"></script>
    <script src="/assets/js/vue-app.js?h=31dcc54fab006baede4b185cb32ae2b0"></script>
    <script src="/assets/js/common.js?h=286dec064320f6492d549d2b9540118f"></script>
    <script src="/assets/js/fileSaver.js?h=3dc79a489531e4f96ebcb674709ec092"></script>
</body>

</html>

templates/layout.jinja2
{% import 'macros.jinja2' as macros %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
{#    <meta http-equiv="refresh" content="2">#}
    <title>{% block title %}{% endblock %}</title>

    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css">
    <link rel="stylesheet" href="../static/css/common.css">
    <script src="https://kit.fontawesome.com/dd91a22075.js" crossorigin="anonymous"></script>
    {%- block css %}{% endblock -%}
</head>
<body>
<div id="main-app">
    <nav>
        <a href="{{ url_for('check_ssh.check_ssh') }}">Check SSH</a>
        <a href="{{ url_for('connect_ssh.connect_ssh') }}">Connect SSH</a>
    </nav>
    <div class="data">
        {% block data %}{% endblock %}
    </div>
    <footer>
        {% block footer %}{% endblock %}
    </footer>
</div>
<script>
    for (let link of document.querySelectorAll('nav a')) {
        if (link.href === location.pathname) {
            link.classList.add('active')
        }
    }
</script>
<script src="https://cdn.jsdelivr.net/npm/vue@2.6.12/dist/vue.js"></script>
{% block js %}{% endblock %}
<script>
    const app = new Vue({
        el: '#main-app',
        data: () => {
            return {
                ssh_list: [
                    {ip: '255.255.255.255', username: '0123456789', password: '0123456789', status: ''},
                    {ip: '255.255.255.255', username: '0123456789', password: '0123456789', status: 'live'},
                    {ip: '255.255.255.255', username: '0123456789', password: '0123456789', status: 'die'},
                    {ip: '255.255.255.255', username: '0123456789', password: '0123456789', status: ''},
                    {ip: '255.255.255.255', username: '0123456789', password: '0123456789', status: ''},
                    {ip: '255.255.255.255', username: '0123456789', password: '0123456789', status: ''},
                    {ip: '255.255.255.255', username: '0123456789', password: '0123456789', status: ''},
                    {ip: '255.255.255.255', username: '0123456789', password: '0123456789', status: ''}
                ],
                display_mode: {
                    all: 'table',
                    live: 'table',
                    die: 'table'
                },
                ...window.data
            }
        },
        methods: {
            get_list: function (name) {
                switch (name) {
                    case 'all': return this.ssh_list
                    case 'live': return this.ssh_list.filter(s => s.status === 'live')
                    case 'die': return this.ssh_list.filter(s => s.status === 'die')
                }
            },
            get_display_mode: function (name) {
                return this.display_mode[name]
            },
            toggle_display_mode: function (name) {
                switch (this.display_mode[name]) {
                    case 'table':
                        this.display_mode[name] = 'text';
                        break
                    case 'text':
                        if (name === 'all') {
                            this.parse_text();
                        }
                        this.display_mode[name] = 'table';
                        break;
                }
            },
            get_text: function (name) {
                return this.get_list(name).map(s => Object.values(s).join('|')).join('\n')
            },
            parse_text: function () {
                const text = document.querySelector('#all-list textarea').value
                const new_list = []
                for (let line of text.split('\n')) {
                    try {
                        const data = line.split('|')
                        let status
                        switch (data[3]) {
                            case 'live': status = 'live'; break
                            case 'die': status = 'die'; break
                            default: status = ''
                        }
                        new_list.push({
                            ip: data[0],
                            username: data[1],
                            password: data[2],
                            status: status
                        })
                    } catch (e) {}
                }
                this.ssh_list = new_list
            },
            download_csv: function (name) {
                const blob = new Blob([this.get_text(name)], {type: "text/plain;charset=utf-8"})
                const anchor = document.createElement("a")
                anchor.download = `${name}-list.csv`
                anchor.href = window.URL.createObjectURL(blob)
                anchor.click()
            },
            ...window.methods
        },
        computed: {
            ...window.computed
        },
        watch: {
            ...window.watch
        }
    })
</script>
<script src="https://cdn.jsdelivr.net/gh/eligrey/FileSaver.js@master/dist/FileSaver.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/clipboard@2.0.8/dist/clipboard.min.js"></script>
<script>
    const clipboard = new ClipboardJS('[data-clipboard-text]');
    clipboard.on('success', function (event) {
        const tooltip_text = event.trigger.dataset.tooltip
        event.trigger.dataset.tooltip = "Copied!"
        setTimeout(() => event.trigger.dataset.tooltip = tooltip_text, 1000)
    })
</script>
</body>
</html>